Console.WriteLine("========================");
Console.WriteLine("      EQUIPO C#");
Console.WriteLine("      DAW DEVELOPERS");
Console.WriteLine("========================");
string alumnoA = "Lorenzo";
Console.WriteLine($"Desarrollador 1: {alumnoA}");
string equipo = "Los programadores";
int puntos = 350;
double presupuesto = 50;
double precioFinal = presupuesto + 25;
Console.WriteLine($"Equipo: {equipo}");
Console.WriteLine($"Puntos: {puntos}");
Console.WriteLine($"Presupuesto: {presupuesto} €");
string alumnoB = "Carlos";
Console.WriteLine($"Desarrollador 2: {alumnoB}");
Console.WriteLine("========================");
Console.WriteLine("   PROGRAMA TERMINADO");
Console.WriteLine("   Gracias por jugar");
Console.WriteLine("========================");